### PR TITLE
Load additional data without reloading everything from scratch

### PR DESCRIPTION
**Pull request by RobinM-code**

### CODE REVIEW

**Comment by romanhaa** [comment]
That looks very promising!

It seems like most of the content in `add_additional_data.sh` is very similar to the `create_and_load_everything_from_scratch.sh` script. Is there a simple way to make only one script and run it either in `create_from_scratch` or `append` mode? Correct me if I'm wrong, but wouldn't we only have to make dropping the tables conditional and then use a different `.sql` scheme based on the mode?

**Comment by RobinM-code** [comment]
yes good idea! should be possible :) will look at it today

**Comment by romanhaa** [comment]
I think it would be useful to add documentation somewhere that explains how to use the new function.

**Comment by romanhaa** [comment]
I just realized that this PR is based on the `master` branch while it should be based on the `2002` branch, which contains additional steps. I'll take care of it. And when done, we should rebase the whole branch to master 😅

**Comment by romanhaa** [comment]
Implemented with commit [`e51b42749320fc35e2263e1401257d7550d147e5`](https://github.com/thehyve/genetics-backend/commit/e51b42749320fc35e2263e1401257d7550d147e5).

**Pull request closed without merging**
